# Generated by Django 2.2.3 on 2022-01-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='create',
            new_name='created',
        ),
    ]
